# Generated by Django 5.2 on 2025-10-04 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0002_run_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, null=True, verbose_name="Вес"),
                ),
                ("goals", models.TextField(blank=True, verbose_name="Цели")),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация об атлете",
                "verbose_name_plural": "Информация об атлетах",
            },
        ),
    ]
